import Head from 'next/head'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Page No Longer Exists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="card">
          <h1 className='main-header'>Sorry The Page You Are Looking For Is No Longer Here</h1>
          <p>If you are looking for a new website, or want a redesign of your existing one please check out <a href="http://capecod.world">Cape Cod World.</a> </p>
        </div>
      </main>
    </div>
  )
}
